### ISSUE TITLE
what is the login for this application ?

### ISSUE THREAD

**Issue by mlotfi2005** [indyaah/UserManager#1]
Hi,
Thank you for this application, I downloaded it and run it under ecliopse, for the login I used :+1: username : admin@mail.com
password : admin

got them from the file : InitDataService 

http://localhost:8081/ROOT/
Page not found

Please your help is appreciated.
Thanks.

**Comment by indyaah** [comment]
@mlotfi2005 : Pull latest master. run **mvn tomcat7:run**
Open browser go to localhost:8080/ 
I dont know where did you get 8081 from/??

In earlier code it was 8888.
